(function() {
  if (window.self !== window.top) return;
  const API_BASE = "https://meet.milorada.ru/recording";
  function getCurrentRoomId() { const url = window.location.hash || ""; const match = url.match(/#\/room\/(![^/?#]+)/); return match ? match[1] : null; }
  function getAccessToken() { try { if (window.mxMatrixClientPeg && window.mxMatrixClientPeg.get) { const client = window.mxMatrixClientPeg.get(); if (client && client.getAccessToken) { const token = client.getAccessToken(); if (token) return token; } } } catch (e) {} return localStorage.getItem("mx_access_token"); }
  async function recordingAPI(action, roomId) { const token = getAccessToken(); if (!token) { alert("Не авторизован"); return { error: "no token" }; } try { const r = await fetch(API_BASE + "/api/record/" + action, { method: "POST", headers: { "Content-Type": "application/json", "Authorization": "Bearer " + token }, body: JSON.stringify({ room: roomId }) }); return await r.json(); } catch (e) { return { error: e.message }; } }
  function showStatus(msg, isError) { const el = document.getElementById("record-status-badge"); if (el) { el.textContent = msg; el.style.color = isError ? "red" : "green"; } }
  function addRecordButton() { if (document.getElementById("record-btn-container")) return; const c = document.createElement("div"); c.id = "record-btn-container"; c.style.cssText = "position:fixed;top:60px;right:20px;z-index:9999;display:flex;gap:8px;align-items:center;background:#f5f5f5;padding:10px 15px;border-radius:8px;box-shadow:0 2px 8px rgba(0,0,0,0.1);font-family:sans-serif;"; const startBtn = document.createElement("button"); startBtn.textContent = "🔴 Запись"; startBtn.style.cssText = "padding:8px 12px;background:#e74c3c;color:white;border:none;border-radius:4px;cursor:pointer;font-size:13px;font-weight:bold;"; startBtn.onclick = async () => { const roomId = getCurrentRoomId(); if (!roomId) { alert("Комната не определена"); return; } startBtn.disabled = true; showStatus("Запуск..."); const res = await recordingAPI("start", roomId); if (res.error) { showStatus("❌ " + res.error, true); startBtn.disabled = false; } else { showStatus("✅ Идёт", false); startBtn.style.display = "none"; stopBtn.style.display = "inline-block"; } }; const stopBtn = document.createElement("button"); stopBtn.textContent = "⏹️ Стоп"; stopBtn.style.cssText = "padding:8px 12px;background:#27ae60;color:white;border:none;border-radius:4px;cursor:pointer;font-size:13px;font-weight:bold;display:none;"; stopBtn.onclick = async () => { const roomId = getCurrentRoomId(); if (!roomId) return; stopBtn.disabled = true; showStatus("Остановка..."); const res = await recordingAPI("stop", roomId); if (res.error) { showStatus("❌ " + res.error, true); stopBtn.disabled = false; } else { showStatus("✅ " + (res.file||""), false); stopBtn.style.display = "none"; startBtn.style.display = "inline-block"; startBtn.disabled = false; } }; const badge = document.createElement("span"); badge.id = "record-status-badge"; badge.textContent = "Готов"; badge.style.cssText = "font-size:12px;color:#666;font-weight:bold;"; c.appendChild(startBtn); c.appendChild(stopBtn); c.appendChild(badge); document.body.appendChild(c); }
  const observer = new MutationObserver(() => { if (document.body && !document.getElementById("record-btn-container")) addRecordButton(); });
  observer.observe(document, { childList: true, subtree: true });
  if (document.body) addRecordButton();
})();
